import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { Settings, MessageCircleDashed, Star, Filter, PencilLine, Search } from "lucide-react";
import ContactLayout from "~/components/ContactLayout";
import { useState } from "react";
// import Contact from "~/components/ContactLayout";

export default function Home() {
    const hello = api.post.hello.useQuery({ text: "from tRPC" });

    const [ContactClicked, setContactClicked] = useState<boolean>(false);

    const SidebarIcons = [
        <MessageCircleDashed style={{ strokeWidth: "1.5" }} />,
        <Star style={{ strokeWidth: "1.5" }} />,
        <Settings style={{ strokeWidth: "1.5" }} />,
    ]

    const Sidebar: React.FC = () => {
        return (
            <div className="w-[4.5rem] h-[95vh] bg-blue-300 flex flex-col justify-between items-center py-4 rounded-l-md">
                <div className="flex flex-col space-y-5">
                    {
                        SidebarIcons.map((icon, idx) => (
                            <button className="hover:cursor-pointer p-[0.3rem] rounded-md focus:bg-blue-200 focus:border-black" key={idx}>
                                {icon}
                            </button>
                        ))
                    }
                </div>
                <button className="w-[24px] h-[24px] rounded-full border-[1px] border-black hover:cursor-pointer focus-within:bg-black">

                </button>
            </div>
        )
    }

    const Chatbox: React.FC = () => {
        return (
            <div className="w-[75%] h-[95vh] bg-blue-400 max-sm:w-full rounded-r-md">
                <span>Start chatting </span>
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>bubble</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex justify-center items-center min-h-screen w-full overflow-hidden bg-blue-400 px-6 overscroll-none" >
                <Sidebar />
                <ContactLayout />
                <Chatbox />
            </main>

        </>
    );
}
